### ISSUE TITLE
Command to reveal config file

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/taxi#117]
It’s often difficult to remember where the taxi config file is located. A command like `taxi config` which either reveal the file path or open it in the $EDITOR would be a good addition.

**Comment by sephii** [comment]
Fixed in https://github.com/liip/taxi/commit/d6c3c085337b6463bc91d696cc7036e62627e072. You can now run taxi in verbose mode to see the configuration file location. The procedure is [detailed in the docs](https://taxi-timesheets.readthedocs.io/en/master/userguide.html#configuration).
