### ISSUE TITLE
Highlight roles matching activity project's circle

### ISSUE THREAD

**Issue by LeBenLeBen** [liip/taxi#120]
Activities are linked to projects, which are each assigned to a single circle. It would be awesome if the role list would highlight roles that match the project circle.

To be checked with others’ usage but in my case we could even limit the list to the roles that matches OR all if none matches. A keypress or command would allow to expand the list though. For example pressing Enter without a number.

**Comment by sephii** [comment]
Done in https://github.com/sephii/taxi-zebra/commit/0b42dbe2e4796b06d7cb25989125b4a14a4486c4, released in taxi-zebra 2.0. 🎉
