### ISSUE TITLE
Clean up user documentation wrt config file location

### ISSUE THREAD

**Issue by hannesgassert** [liip/taxi#122]
https://taxi-timesheets.readthedocs.io/en/master/userguide.html gives confusing information regarding the location of the config file, in this order:

* "You will need a configuration file (~/.taxirc)"
* "by default ~/.config/taxi/taxirc"
* "by default ~/.config/taxi/taxirc or ~/.taxirc"
* "Linux: ~/.local/share/taxi/.taxirc, OS X: ~/Library/Application Support/taxi/.taxirc, Windows: C:\Documents and Settings\<User>\Application Data\Local Settings\sephii\taxi\.taxirc"

For the casual reader it would be more helpful if all the instances referring to a config file would just link to the paragraph about that, instead of giving information that might not be true for them.
On my Mac, none of the locations given where correct, the file got put into ~/Library/Application Support/taxi/taxirc (no dot). 😃 

This issue is related to #117.

**Comment by sephii** [comment]
Thanks for pointing this out, this is definitely something that should be fixed.

**Comment by sephii** [comment]
Fixed in https://github.com/liip/taxi/commit/6c0e1aee1b1482b4d2b7dd27d5cc4202fb8721b9 and https://github.com/liip/taxi/commit/d6c3c085337b6463bc91d696cc7036e62627e072.
